@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":add n/David"

class ModelManager {
    undoAction = Runnable
}

note bottom of ModelManager : Undo action **overwritten**:\nnow deletes David and his tags.\nPrevious undo action is lost.
@enduml
