@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":list"

class ModelManager {
    undoAction = null
}

note bottom of ModelManager : Non-mutating commands do not\nmodify the undo action.\nundoAction remains null.
@enduml
