@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

class ModelManager {
    undoAction = null
}

note bottom of ModelManager : No undo action stored.\n:undo will return an error.
@enduml
