@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":delete 5"

class ModelManager {
    undoAction = Runnable
}

note bottom of ModelManager : Undo action: re-add the\ndeleted person and their tags.
@enduml
