@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command ":undo"

class ModelManager {
    undoAction = null
}

note bottom of ModelManager : Undo action was executed\n(David was deleted) and then cleared.\n:undo again will return an error.
@enduml
